# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Location:
  fields:
    default: name, address, image_file_name
    form: name, address, description, image_file_name
  order_by: 
  relationships: 
  filters: 
  search: name
  application: typus_test

